# Generated by Django 5.2.8 on 2025-12-12 00:53

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blogInfo', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='categoria',
            options={'verbose_name_plural': 'Categorías'},
        ),
        migrations.AlterModelOptions(
            name='comentario',
            options={'ordering': ['fecha_creacion']},
        ),
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['-fecha_publicacion']},
        ),
        migrations.RenameField(
            model_name='comentario',
            old_name='fecha_comentario',
            new_name='fecha_creacion',
        ),
        migrations.RenameField(
            model_name='post',
            old_name='Categorias',
            new_name='categorias',
        ),
        migrations.AddField(
            model_name='autor',
            name='facebook',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='instagram',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='autor',
            name='twitter',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='comentario',
            name='usuario',
            field=models.ForeignKey(default=django.utils.timezone.now, on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='post',
            name='imagen',
            field=models.ImageField(blank=True, null=True, upload_to='img/', verbose_name='Imagen de Portada'),
        ),
        migrations.AddField(
            model_name='post',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=300, null=True, verbose_name='Subtítulo'),
        ),
        migrations.AlterField(
            model_name='categoria',
            name='nombre',
            field=models.CharField(max_length=100),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='autor_comentario',
            field=models.CharField(max_length=200),
        ),
        migrations.AlterField(
            model_name='post',
            name='fecha_actualizacion',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
