# Generated by Django 5.2.8 on 2025-12-12 02:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blogInfo', '0002_alter_categoria_options_alter_comentario_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='post',
            options={'ordering': ['fecha_publicacion']},
        ),
    ]
